services:
  db:
    image: postgres:15
    container_name: postgres_news_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: news_portal
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
