services:
  backend:
    build: ./backend
    container_name: nest_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/src
      - /src/node_modules
    command: npm run start:dev
    networks:
      - app-network
    restart: unless-stopped
    
  tests:
    build: ./tests
    container_name: bias_tests
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:3000
    volumes:
      - ./tests:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./frontend:/src
      - /src/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres_news_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_portal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
